spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/data-jpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
  #       show_sql: true // 콘솔에 정보 남기는 게 아닌 log파일에 처리
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace